# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/Modeltech_pe_10.4c/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Ray/Vivado/Music_Looper/Music_Looper.cache/wt [current_project]
set_property parent.project_path D:/Ray/Vivado/Music_Looper/Music_Looper.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet d:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/ip/mig_7series_0/mig_7series_0.dcp
set_property used_in_implementation false [get_files d:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/ip/mig_7series_0/mig_7series_0.dcp]
read_verilog -library xil_defaultlib {
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Bit_Getter.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/PWM_Trans.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Mic_Input.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Memory_Control.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Light_Output.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Main_Control.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Debounce.v
  D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/new/Looper_Top.v
}
read_vhdl -library xil_defaultlib D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/sources_1/imports/hdl/Ram2Ddr.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/constrs_1/new/XDC.xdc
set_property used_in_implementation false [get_files D:/Ray/Vivado/Music_Looper/Music_Looper.srcs/constrs_1/new/XDC.xdc]


synth_design -top Looper_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Looper_Top.dcp

catch { report_utilization -file Looper_Top_utilization_synth.rpt -pb Looper_Top_utilization_synth.pb }
